# Site settings
title: Hicham El Hammouchi
email: hicham.elhammouchi@gmail.com
url: https://melxx001.github.io
description: "Thoughts, posts and code sample by Hicham El Hammouchi. Follow me on twitter @helhammo."
version: 0.0.1

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Hicham El Hammouchi
  location: Location
  social: Around the Web
  quotes: Quotes

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/helhammo
  - title: linkedin
    url: https://www.linkedin.com/pub/hicham-el-hammouchi/39/268/193
  - title: github
    url: http://github.com/melxx001
  - title: stack-overflow
    url: http://stackoverflow.com/users/4935677/hicham-el-hammouchi

# Postal address (add as many lines as necessary)
address:
  - line: 221B Baker Street

# quotest content
quotes: 'When you have eliminated all which is impossible, then whatever remains, however improbable, must be the truth'
author: 'Sherlock Holmes'

# Build settings
markdown: kramdown
permalink: pretty
